// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messagefrmt.proto

package main

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Kipcntxtmessage_MsgType int32

const (
	Kipcntxtmessage_QUERY    Kipcntxtmessage_MsgType = 0
	Kipcntxtmessage_RESPONSE Kipcntxtmessage_MsgType = 1
)

var Kipcntxtmessage_MsgType_name = map[int32]string{
	0: "QUERY",
	1: "RESPONSE",
}

var Kipcntxtmessage_MsgType_value = map[string]int32{
	"QUERY":    0,
	"RESPONSE": 1,
}

func (x Kipcntxtmessage_MsgType) String() string {
	return proto.EnumName(Kipcntxtmessage_MsgType_name, int32(x))
}

func (Kipcntxtmessage_MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_53b2d96e84549a01, []int{0, 0}
}

type Kipcntxtmessage struct {
	Type                 Kipcntxtmessage_MsgType `protobuf:"varint,1,opt,name=type,proto3,enum=main.Kipcntxtmessage_MsgType" json:"type,omitempty"`
	Data                 string                  `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Sid                  string                  `protobuf:"bytes,3,opt,name=sid,proto3" json:"sid,omitempty"`
	Delimiter            string                  `protobuf:"bytes,4,opt,name=Delimiter,json=delimiter,proto3" json:"Delimiter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Kipcntxtmessage) Reset()         { *m = Kipcntxtmessage{} }
func (m *Kipcntxtmessage) String() string { return proto.CompactTextString(m) }
func (*Kipcntxtmessage) ProtoMessage()    {}
func (*Kipcntxtmessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_53b2d96e84549a01, []int{0}
}

func (m *Kipcntxtmessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kipcntxtmessage.Unmarshal(m, b)
}
func (m *Kipcntxtmessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kipcntxtmessage.Marshal(b, m, deterministic)
}
func (m *Kipcntxtmessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kipcntxtmessage.Merge(m, src)
}
func (m *Kipcntxtmessage) XXX_Size() int {
	return xxx_messageInfo_Kipcntxtmessage.Size(m)
}
func (m *Kipcntxtmessage) XXX_DiscardUnknown() {
	xxx_messageInfo_Kipcntxtmessage.DiscardUnknown(m)
}

var xxx_messageInfo_Kipcntxtmessage proto.InternalMessageInfo

func (m *Kipcntxtmessage) GetType() Kipcntxtmessage_MsgType {
	if m != nil {
		return m.Type
	}
	return Kipcntxtmessage_QUERY
}

func (m *Kipcntxtmessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Kipcntxtmessage) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *Kipcntxtmessage) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func init() {
	proto.RegisterEnum("main.Kipcntxtmessage_MsgType", Kipcntxtmessage_MsgType_name, Kipcntxtmessage_MsgType_value)
	proto.RegisterType((*Kipcntxtmessage)(nil), "main.kipcntxtmessage")
}

func init() { proto.RegisterFile("messagefrmt.proto", fileDescriptor_53b2d96e84549a01) }

var fileDescriptor_53b2d96e84549a01 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x4d, 0x2b, 0xca, 0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9,
	0x4d, 0xcc, 0xcc, 0x53, 0x5a, 0xc3, 0xc8, 0xc5, 0x9f, 0x9d, 0x59, 0x90, 0x9c, 0x57, 0x52, 0x51,
	0x02, 0x55, 0x23, 0x64, 0xc8, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x67, 0x24, 0xab, 0x07, 0x52, 0xa8, 0x87, 0xa6, 0x48, 0xcf, 0xb7, 0x38, 0x3d, 0xa4, 0xb2, 0x20,
	0x35, 0x08, 0xac, 0x54, 0x48, 0x88, 0x8b, 0x25, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x49, 0x81, 0x51,
	0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe0, 0x62, 0x2e, 0xce, 0x4c, 0x91, 0x60, 0x06, 0x0b, 0x81,
	0x98, 0x42, 0x32, 0x5c, 0x9c, 0x2e, 0xa9, 0x39, 0x99, 0xb9, 0x99, 0x25, 0xa9, 0x45, 0x12, 0x2c,
	0x60, 0x71, 0xce, 0x14, 0x98, 0x80, 0x92, 0x12, 0x17, 0x3b, 0xd4, 0x50, 0x21, 0x4e, 0x2e, 0xd6,
	0xc0, 0x50, 0xd7, 0xa0, 0x48, 0x01, 0x06, 0x21, 0x1e, 0x2e, 0x8e, 0x20, 0xd7, 0xe0, 0x00, 0x7f,
	0xbf, 0x60, 0x57, 0x01, 0xc6, 0x24, 0x36, 0xb0, 0xdb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x1d, 0xfb, 0x1d, 0x7b, 0xd0, 0x00, 0x00, 0x00,
}
